provider: google
model: gemini-2.5-flash
embedding_provider: google
embedding_model: gemini-embedding-001
quality: max
output_dir: .autodoc
include:
  - "**/*"
exclude:
  - "node_modules/**"
  - "vendor/**"
  - ".git/**"
  - "dist/**"
  - ".autodoc/**"
  - ".claude/**"
  - "testdata/**"
  - "*.exe"
logo: assets/logo.png
max_concurrency: 1
ci:
  auto_commit: true
  fail_on_error: false
